# Generated by Django 3.1.1 on 2020-09-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_adress', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
