# Generated by Django 3.1.1 on 2020-09-15 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_adress', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('begin_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('comentary', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'session_user',
            },
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('hash_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'hash',
            },
        ),
    ]
