# Generated by Django 3.1.1 on 2020-09-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('session_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('begin_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('comentary', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'session_user',
            },
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('hash_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'hash',
            },
        ),
    ]
